backend:
  name: git-gateway
  repo: liminalfun/valeriecrawford
  branch: master

local_backend: true

media_library:
  name: uploadcare
  config:
    publicKey: 414af48ed6e30290fd36
    tabs: 'file url'
  settings:
    autoFilename: true

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "sinthome" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Sinthome Collection" # Used in the UI, ie.: "New Post"
    label_singular: "Jewelry Piece"
    folder: "site/content/sinthome" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Name", name: "title", widget: "string" }
      - label: "Stripe link"
        name: "link"
        widget: "string"
        required: false
      - label: "Description"
        name: "description"
        widget: "markdown"
        required: false
      - { label: "Price", name: "price", widget: "number", required: false }
      - label: "Images"
        name: "images"
        widget: "list"
        required: false
        fields:
          - label: "Image"
            name: "image"
            widget: "object"
            required: false
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string", required: false}
              - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }

  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          - label: "Intro Section"
            name: "intro"
            widget: "object"
            fields:
              - label: "Left Image"
                name: "left"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false}
                  - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
              - label: "Right Image"
                name: "right"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false}
                  - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
              - label: "Center Logo"
                name: "center"
                widget: "image"
                required: false
          - label: "Content"
            name: "content"
            widget: list
            summary: "Section"
            fields:
              - label: "Section"
                name: "section"
                widget: "object"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "object"
                    required: false
                    fields:
                      - { label: "Image", name: "image", widget: "image" }
                      - { label: "Alt Text", name: "alt", widget: "string", required: false}
                      - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
                  - label: "Text blurb"
                    name: "text"
                    widget: "object"
                    fields: 
                      - label: "Text"
                        name: "text"
                        widget: markdown
                        required: false
                        buttons: [link, bold, italic]
                        editor_components: []
                      - { label: "Color", name: "color", widget: "select", required: false, options: ["color-white", "color-dark"]}
                  - label: "Link"
                    name: "link"
                    widget: "object"
                    required: false
                    fields:
                      - { label: "Link Label", name: "label", widget: "string", required: false}
                      - { label: "Link URL", name: "url", widget: "string", required: false }
                      - { label: "Style", name: "placement", widget: "select", required: false, options: ["line-bottom", "bottom"]}
                      - { label: "Line on left", name: "line", widget: "select", required: false, options: ["Yes", "No"]}
              
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: body, widget: markdown, minimal: true, buttons: [link, bold, italic], editor_compoents: [], required: false }
          - label: FAQ
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: markdown
                minimal: true
                buttons: [link, bold, italic]
                editor_components: []
          - label: Contact Form
            name: form
            widget: object
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Email, name: email, widget: string }
              - { label: Message, name: message, widget: string }
              - { label: Submit Button, name: btn, widget: string }
      - file: "site/content/shop/_index.md"
        label: "Shop Page"
        name: "shop"
        fields:
          - { label: Page Title, name: title, widget: hidden, default: "Shop" }
          - { label: Collection Title, name: heading, widget: string }
          - label: "Shop description"
            name: "description"
            widget: markdown
            required: false
            buttons: [link, bold, italic]
            editor_components: []
          - label: "Link"
            name: "link"
            widget: "object"
            required: false
            fields:
              - { label: "Link Label", name: "label", widget: "string", required: false}
              - { label: "Link URL", name: "url", widget: "string", required: false }
      - file: "site/content/process/_index.md"
        label: "Process Page"
        name: "process"
        fields:
          - { label: Title, name: title, widget: string }
          - label: "Section 1"
            name: "section_01"
            widget: object
            summary: "Section"
            fields:
              - label: "Text blurb"
                name: "text"
                widget: "object"
                fields: 
                  - label: "Text 1"
                    name: "text_01"
                    widget: markdown
                    required: false
                    buttons: [link, bold, italic]
                    editor_components: []
                  - label: "Text 2"
                    name: "text_02"
                    widget: markdown
                    required: false
                    buttons: [link, bold, italic]
                    editor_components: []
              - label: "Image 1"
                name: "image_01"
                widget: "object"
                required: false
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false}
                  - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
              - label: "Image 2"
                name: "image_02"
                widget: "object"
                required: false
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false}
                  - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
              - label: "Image 3"
                name: "image_03"
                widget: "object"
                required: false
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false}
                  - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
              - label: "Image 4"
                name: "image_04"
                widget: "object"
                required: false
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false}
                  - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
          - label: "Section 2"
            name: "section_02"
            widget: object
            hint: "Full-width image with text in middle"
            summary: "Section"
            fields:
              - label: "Image"
                name: "image"
                widget: "object"
                required: false
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false}
                  - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
              - label: "Text blurb"
                name: "text"
                widget: "object"
                fields: 
                  - label: "Text"
                    name: "text"
                    widget: markdown
                    required: false
                    buttons: [link, bold, italic]
                    editor_components: []
                  - { label: "Color", name: "color", widget: "select", required: false, options: ["color-white", "color-dark"]}
          - label: "Section 3"
            name: "section_03"
            widget: object
            summary: "Section"
            fields:
              - label: "Overlapping images"
                name: "overlap"
                widget: "object"
                required: false
                fields:
                - label: "Image on Bottom"
                  name: "image_bottom"
                  widget: "object"
                  required: false
                  fields:
                    - { label: "Image", name: "image", widget: "image" }
                    - { label: "Alt Text", name: "alt", widget: "string", required: false}
                    - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
                - label: "Image on Top"
                  name: "image_top"
                  widget: "object"
                  required: false
                  fields:
                    - { label: "Image", name: "image", widget: "image" }
                    - { label: "Alt Text", name: "alt", widget: "string", required: false}
                    - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
              - label: "Text blurb"
                name: "text"
                widget: "object"
                fields: 
                  - label: "Text"
                    name: "text"
                    widget: markdown
                    required: false
                    buttons: [link, bold, italic]
                    editor_components: []
                  - { label: "Color", name: "color", widget: "select", required: false, options: ["color-white", "color-dark"]}
          - label: "Section 4"
            name: "section_04"
            widget: object
            hint: "Full-width image with two text blurbs"
            summary: "Section"
            fields:
              - label: "Image"
                name: "image"
                widget: "object"
                required: false
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false}
                  - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
              - label: "Text blurb on top"
                name: "text_top"
                widget: "object"
                fields: 
                  - label: "Text"
                    name: "text"
                    widget: markdown
                    required: false
                    buttons: [link, bold, italic]
                    editor_components: []
                  - { label: "Color", name: "color", widget: "select", required: false, options: ["color-white", "color-dark"]}
              - label: "Text blurb on bottom"
                name: "text_bottom"
                widget: "object"
                fields: 
                  - label: "Text"
                    name: "text"
                    widget: markdown
                    required: false
                    buttons: [link, bold, italic]
                    editor_components: []
                  - { label: "Color", name: "color", widget: "select", required: false, options: ["color-white", "color-dark"]}
          - label: "Section 5"
            name: "section_05"
            widget: object
            hint: "Half-width image with skematic poem"
            summary: "Section"
            fields:
              - label: "Image"
                name: "image"
                widget: "object"
                required: false
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false}
                  - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
              - label: "Text 1"
                name: "text_01"
                widget: "string"
                required: false
              - label: "Text 2"
                name: "text_02"
                widget: "string"
                required: false
              - label: "Text 3"
                name: "text_03"
                widget: "string"
                required: false
              - label: "Text 4"
                name: "text_04"
                widget: "string"
                required: false
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "site/config/_default/params.toml"
        label: "Settings"
        name: "settings"
        fields:
          - { label: "Marquee", name: "marquee", widget: "text", required: false }
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "Social preview image", name: "seo_preview", widget: "image", hint: "Image for previews on social media & chat apps" }
          - { label: "SEO description", name: "seo_description", widget: "text", hint: "50-100 words to appear in search results, and in previews on social media & chat apps" }