backend:
  name: git-gateway
  repo: liminalfun/valeriecrawford
  branch: master

local_backend: true

media_library:
  name: uploadcare
  config:
    publicKey: 414af48ed6e30290fd36
  settings:
    autoFilename: true

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "piece" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Sinthome Collection" # Used in the UI, ie.: "New Post"
    label_singular: "Jewelry Piece"
    folder: "site/content/sinthome" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Name", name: "title", widget: "string" }
      - label: "Stripe link"
        name: "link"
        widget: "string"
        required: false
      - label: "Description"
        name: "description"
        widget: "markdown"
        required: false
      - { label: "Price", name: "price", widget: "number", required: false }
      - label: "Images"
        name: "images"
        widget: "list"
        required: false
        fields:
          - label: "Image"
            name: "image"
            widget: "object"
            required: false
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string", required: false}
              - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }

  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          - label: "Intro Section"
            name: "intro"
            widget: "object"
            fields:
              - label: "Left Image"
                name: "left"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false}
                  - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
              - label: "Right Image"
                name: "right"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false}
                  - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
              - label: "Center Logo"
                name: "center"
                widget: "image"
                required: false
          - label: "Content"
            name: "content"
            widget: list
            summary: "Section"
            fields:
              - label: "Section"
                name: "section"
                widget: "object"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "object"
                    required: false
                    fields:
                      - { label: "Image", name: "image", widget: "image" }
                      - { label: "Alt Text", name: "alt", widget: "string", required: false}
                      - { label: "Credit", name: "credit", widget: "markdown", required: false, minimal: true, buttons: [link, bold, italic], editor_components: [] }
                  - label: "Text blurb"
                    name: "text"
                    widget: "object"
                    fields: 
                      - label: "Text"
                        name: "text"
                        widget: markdown
                        required: false
                        buttons: [link, bold, italic]
                        editor_components: []
                      - { label: "Color", name: "color", widget: "select", required: false, options: ["color-white", "color-dark"]}
                  - label: "Link"
                    name: "link"
                    widget: "object"
                    required: false
                    fields:
                      - { label: "Link Label", name: "label", widget: "string", required: false}
                      - { label: "Link URL", name: "url", widget: "string", required: false }
                      - { label: "Style", name: "placement", widget: "select", required: false, options: ["line-bottom", "bottom"]}
                      - { label: "Line on left", name: "line", widget: "select", required: false, options: ["Yes", "No"]}
              
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: body, widget: markdown }
          - label: FAQ
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: markdown
                minimal: true
                buttons: [link, bold, italic]
                editor_components: []
      - file: "site/content/shop/_index.md"
        label: "Shop Page"
        name: "shop"
        fields:
          - { label: Page Title, name: title, widget: hidden, default: "Shop" }
          - { label: Collection Title, name: heading, widget: string }
          - label: "Shop description"
            name: "description"
            widget: markdown
            required: false
            buttons: [link, bold, italic]
            editor_components: []
          - label: "Link"
            name: "link"
            widget: "object"
            required: false
            fields:
              - { label: "Link Label", name: "label", widget: "string", required: false}
              - { label: "Link URL", name: "url", widget: "string", required: false }
      - file: "site/content/process/_index.md"
        label: "Process Page"
        name: "process"
        fields:
          - { label: Title, name: title, widget: string }
