backend:
  name: git-gateway
  repo: liminalfun/valeriecrawford
  branch: master

local_backend: true

media_library:
  name: uploadcare
  config:
    publicKey: 414af48ed6e30290fd36
  settings:
    autoFilename: true

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "piece" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Sinthome Collection" # Used in the UI, ie.: "New Post"
    label_singular: "Jewelry Piece"
    folder: "site/content/sinthome" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Name", name: "title", widget: "string" }
      - {
          label: "Stripe link",
          name: "link",
          widget: "string",
          required: false,
        }
      - {
          label: "Description",
          name: "description",
          widget: "markdown",
          required: false,
        }
      - { label: "Price", name: "price", widget: "number", required: false }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          required: false,
          fields:
            [
              {
                label: "Image",
                name: "img",
                widget: "object",
                required: false,
                fields:
                  [
                    { label: "Image", name: "image", widget: "image" },
                    {
                      label: "Alt Text",
                      name: "alt",
                      widget: "string",
                      required: false,
                    },
                    {
                      label: "Link",
                      name: "link",
                      widget: "string",
                      required: false,
                    },
                    {
                      label: "Credit",
                      name: "credit",
                      widget: "string",
                      required: false,
                    },
                  ],
              },
            ],
        }

  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "Content",
              name: content,
              widget: list,
              fields:
                [
                  {
                    label: "Image",
                    name: "img",
                    widget: "object",
                    required: false,
                    collapsed: true,
                    fields:
                      [
                        { label: "Image", name: "image", widget: "image" },
                        {
                          label: "Alt Text",
                          name: "alt",
                          widget: "string",
                          required: false,
                        },
                        {
                          label: "Link",
                          name: "link",
                          widget: "string",
                          required: false,
                        },
                        {
                          label: "Caption",
                          name: "caption",
                          widget: "string",
                          required: false,
                        },
                      ],
                  },
                  {
                    label: "Heading",
                    name: "heading",
                    widget: "string",
                    required: false,
                  },
                  {
                    label: "Text",
                    name: "text",
                    widget: "markdown",
                    required: false,
                  },
                ],
              {
                label: "Button",
                name: "btn",
                widget: "object",
                required: false,
                collapsed: true,
                fields:
                  [
                    {
                      label: "Text",
                      name: "text",
                      widget: "string",
                      required: false,
                    },
                    {
                      label: "Link",
                      name: "link",
                      widget: "string",
                      required: false,
                    },
                  ],
              },
            }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Image, name: image, widget: image }
          - {
              label: "Blurb",
              name: blurb,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
          - {
              label: "Intro",
              name: intro,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }

      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Logo, name: logo, widget: image }
          - { label: Body, name: body, widget: markdown }
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/shop/_index.md"
        label: "Shop Page"
        name: "shop"
        fields:
          - { label: Page Title, name: title, widget: hidden, default: "Shop" }
          - { label: Collection Title, name: heading, widget: string }
          - {
              label: Description,
              name: description,
              widget: markdown,
              required: false,
            }
          - {
              label: "Jewlery Piece",
              name: "piece",
              widget: "relation",
              collection: "sinthome",
              search_fields: ["title", "price"],
              value_field: "title",
              required: false,
            }
          - {
              label: Collection Items,
              name: collection,
              widget: list,
              required: false,
              fields:
                [
                  {
                    label: "Jewlery Piece",
                    name: "piece",
                    widget: "relation",
                    collection: "post",
                    search_fields: ["title"],
                    value_field: "title",
                    display_field: ["title"],
                    required: false,
                  },
                ],
            }
      - file: "site/content/process/_index.md"
        label: "Process Page"
        name: "process"
        fields:
          - { label: Title, name: title, widget: string }
